### PR TITLE
Created instrument addon ethernet protocol listener vi

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-classes/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-classes/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Added a new ListenerVi.vi along with Listener Class and methods which facilitates the testing of the protocols defined under Protocols.lvlib

### Why should this Pull Request be merged?

Adds the ListenerVi.vi with the necessary support files to the project

### What testing has been done?

All tests run locally passed.

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Rename this virtual folder to Listener:
image

**Comment by bogdanp-ni** [comment]
This VI can be deleted, it is just a plain wrapper over another call:
image

**Comment by bogdanp-ni** [comment]
There shouldn't be an "AK?" input to any of these VIs, that information can be extracted from the Protocol object being sent in. Another argument for this is that there's no "AK UDP" implementation, that combination of parameters would be invalid.

image

**Comment by bogdanp-ni** [comment]
Protocols.lvlib should not be in the Tests virtual folder:
image

**Comment by bogdanp-ni** [comment]
Rename "Network Operation" to "Execute Network Operation".

**Comment by bogdanp-ni** [comment]
Rename "Close Ref" to "Close Reference" and capitalize all words for "Set protocol data" -> "Set Protocol Data"

**Comment by bogdanp-ni** [comment]
Rename "Protocol Ctl.ctl" to just "Protocol.ctl"

**Comment by bogdanp-ni** [comment]
Also regarding naming: instead of TCP IP and TCP_IP used interchangeably, standardize on TCP in all your usages.

**Comment by bogdanp-ni** [comment]
Fix the node covering the structure here:
image

**Comment by bogdanp-ni** [comment]
Clean up the error wire in all your VIs.

**Comment by zszilagy** [comment]
> Rename this virtual folder to Listener:
> ![image](https://user-images.githubusercontent.com/61490253/78673779-49430c80-78eb-11ea-9fc7-a24c468ac99f.png

**Comment by zszilagy** [comment]
Closed accidentally.

**Pull request merged**
