### PR TITLE
Created protocol factories and unit tests

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-classes/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Adds a factory method which takes a **<Protocol name>** Settings.ctl type definition as an input parameter, and return a **<Protocol Name>** object with the provided settings.
It also adds unit tests which verifies the functionality of these factory methods.

### Why should this Pull Request be merged?

The protocol factory methods are needed by the Instrument Addon Scripting API.
The tests are necessary to validate the functionality of the factory methods.

### What testing has been done?

Wrote unit tests, run them locally and they all passed.

### CODE REVIEW

**Review by phutanu — CHANGES_REQUESTED** [review]
Please rename: 
- "test_AK Rs-xxx Protocol Factory.vi" into "test_AK RS-xxx Protocol Factory.vi" (upper case S in RS-xxx)

**Review by phutanu — CHANGES_REQUESTED** [review]
Please revert the "UDP/Methods/Error Cleanup.vi" as no change has been done to it (functional or major visual improvement).

**Review by phutanu — CHANGES_REQUESTED** [review]
Please include for each of the Protocol controls the template icon specific for each class. And maybe some glyph to suggest settings.

**Review by phutanu — CHANGES_REQUESTED** [review]
Please remove the "Current Command Code" from the AK VIs and AK controls as this is managed automatically by the Protocol Engine (specifically in the Write VIs) and not by the user.

**Review by phutanu — COMMENTED** [review]
Please remove the VI: "test_AK Rs-xxx Protocol Factory.vi" from the physical folder also.

**Comment by bogdanp-ni** [comment]
I want us to strive for consistency, therefore all typedef inputs to Factories should be called using the same pattern "protocol_name Settings". I saw some of them being called "* PortSettings", please correct that.

**Comment by bogdanp-ni** [comment]
Typo in UDP Factory -> name of typedef input is "UPD *"

**Comment by bogdanp-ni** [comment]
For Convbox, typedef input must have the word "settings" starting with capital "S".

**Comment by bogdanp-ni** [comment]
Current Command Code should not be part of the user visible settings of AK protocols.

**Review by phutanu — APPROVED** [review]

**Review by phutanu — COMMENTED** [review]
I noticed that for some protocols we have access straight to each of the setting, for others they are contained inside a "Protocol Settings" cluster. Is there a reason for this? We would want to have similar implementation for all of them, for consistency reasons.
Also, for "AK RS-xxx Settings.ctl" there is a Cluster with the protocol settings inside another cluster. I think there is no need for that.

**Comment by bogdanp-ni** [comment]
For AK RS-xxx, I still see a "PortSettings" cluster, are we keeping that?

**Comment by phutanu** [comment]
> For AK RS-xxx, I still see a "PortSettings" cluster, are we keeping that?

It's the same in the current implementation of "RS-xxx" and "AK RS-xxx". If we change that than we would need to update all other VIs that access this property.

**Comment by phutanu** [comment]
For the test VIs icons, could you please erase the "Example" text and maybe add some text specific for each protocol?

**Comment by zszilagy** [comment]
> For the test VIs icons, could you please erase the "Example" text and maybe add some text specific for each protocol?

Changed as suggested

**Review by phutanu — APPROVED** [review]

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
