### PR TITLE
Review "Get protocol type.vi"

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-classes/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

The following updates were made to the "Get Protocol Type.vi" VIs:
- Added universal description (documentation)
- Updated the Icon as it was only set for the one in the protocol parent class. Connecting any other class to the protocol parent protocol in input resulted in a blank icon.
- Performed Ctrl+Space, Ctrl+F cleanup on each VI
- Changed input/output name according to the feature spec

### Why should this Pull Request be merged?
The current VIs do not correspond to the standards set by the feature spec. documentaiton.

### What testing has been done?

n/a

### CODE REVIEW

**Comment by phutanu** [comment]
Something strange happened with the "protocol type" terminal on almost all the "Get Protocol Type.vi" nodes.
Please check all of them and adjust accordingly.

image

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comment.

**Review by bogdanp-ni — APPROVED** [review]
Please fix the comment from phutanu.

**Comment by zszilagy** [comment]
> Something strange happened with the "protocol type" terminal on almost all the "Get Protocol Type.vi" nodes.
> Please check all of them and adjust accordingly.
> 
> image

Fixed.

**Comment by phutanu** [comment]
> > Something strange happened with the "protocol type" terminal on almost all the "Get Protocol Type.vi" nodes.
> > Please check all of them and adjust accordingly.
> > image
> 
> Fixed.

There is more than one node. I put AK RS-xxx just as an example.
But it can be seen also inside:
- AK TCP.lvclass--Get Protocol Type.vi
- Protocol Parent.lvclass--Get Protocol Type.vi
- RS-xxx to GPIB ConvBox.lvclass--Get Protocol Type.vi
- etc.

So please check all the "Get Protocol Type.vi" nodes for this anomaly.

**Review by phutanu — CHANGES_REQUESTED** [review]
> > Something strange happened with the "protocol type" terminal on almost all the "Get Protocol Type.vi" nodes.
> > Please check all of them and adjust accordingly.
> > image
> 
> Fixed.

There is more than one node. I put AK RS-xxx just as an example.
But it can be seen also inside:
- AK TCP.lvclass--Get Protocol Type.vi
- Protocol Parent.lvclass--Get Protocol Type.vi
- RS-xxx to GPIB ConvBox.lvclass--Get Protocol Type.vi
- etc.

So please check all the "Get Protocol Type.vi" nodes for this.

**Review by phutanu — APPROVED** [review]

**Pull request merged**
