### PR TITLE
Added Icon/Description for Get Protocol Type.vi (Every instance) and unit tests

### PR DESCRIPTION
**Pull request by zszilagy**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-classes/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR adds icon for each **Get Protocol Type.vi,** as well as description for each VI.
It also adds unit tests which validates the functionality of these VIs were also added.
Also, the icons of Get Base Protocol.vi was also updated in every instance as in order to distinguish them easily form the Get Protocol Type.vi
Fixes a unit test which was failing.

### Why should this Pull Request be merged?

The **Get Protocol Type.vi**'s functionality was already implemented, but it had empty (default) icons.
Every VI lacked the mandatory descriptions.
Unit test called "test_AK RS-xxx Protocol Factory.vi was failing.

### What testing has been done?

Run the unit tests locally and they all passed.
Built the protocols library locally and the build passed.

### CODE REVIEW

**Comment by phutanu** [comment]
Great job, Zoli! 🥇

**Comment by bogdanp-ni** [comment]
I see that Get Base Protocol VIs don't have an error case structure, while Get Protocol Type VIs have it. Why is that?

**Comment by zszilagy** [comment]
> I see that Get Base Protocol VIs don't have an error case structure, while Get Protocol Type VIs have it. Why is that?

Well the Get Base Protocol VIs were not implemented by us. Adding case structure to these VIs would mean that we do refactoring. At this point refactoring original VIs is out of our scope. Do you think that we should do it?

**Comment by bogdanp-ni** [comment]
> > I see that Get Base Protocol VIs don't have an error case structure, while Get Protocol Type VIs have it. Why is that?
> 
> Well the Get Base Protocol VIs were not implemented by us. Adding case structure to these VIs would mean that we do refactoring. At this point refactoring original VIs is out of our scope.

Refactoring is never out of scope, as long as it makes sense to do it. We are always following the Boy Scout Rule. Since this refactor is a low-hanging fruit, then we can definitely do it.

> Do you think that we should do it?

That one's for you to answer :) what's the behavior you want these VIs to exhibit?

**Review by bogdanp-ni — APPROVED** [review]

**Pull request merged**
