### PR TITLE
Refactored the factory methods into a polymorphic vi. Did review checklist on each VI.

### PR DESCRIPTION
**Pull request by zszilagy**
- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-instrument-addon-classes/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

The factory methods were refactored into a polymorphic VI called "Protocol Factory".
Fixed control/indicator arrangement of the factory method VIs.
Fixed block diagram arrangement of the factory methods.
Renamed controls/indicators according to the guidelines.

### Why should this Pull Request be merged?

In they current form none of the VIs match the expected visual guideline.

### What testing has been done?

n/a

### CODE REVIEW

**Comment by bogdanp-ni** [comment]
Please add documentation (one-liner) for each VI.

**Comment by zszilagy** [comment]
> Please add documentation (one-liner) for each VI. Don't describe each terminal.

Fixed as requested.

**Comment by phutanu** [comment]
Protocol Factory.vi -> Please update: 
- the input terminal should be: "protocol settings"
- the output terminal should be: "protocol out"
- the icon should be the one from the spec (the same as each instance of the protocol polymorphic vi), just the header is different
- please make the polymorphic VI selector visible by default

image

**Comment by phutanu** [comment]
> > Please add documentation (one-liner) for each VI. Don't describe each terminal.
> 
> Fixed as requested.

Please make sure "RS-xxx Factory.vi" and "AK RS-xxx Factory.vi" both have a one liner documentation. Diff Bot does not show anything for this two VIs.

**Review by phutanu — CHANGES_REQUESTED** [review]
Please check my above comments.

**Review by bogdanp-ni — APPROVED** [review]
Please address any outstanding comments and this is good to go.

**Comment by zszilagy** [comment]
> Protocol Factory.vi -> Please update:
> 
> * the input terminal should be: "protocol settings"
> * the output terminal should be: "protocol out"
> * the icon should be the one from the spec (the same as each instance of the protocol polymorphic vi), just the header is different
> * please make the polymorphic VI selector visible by default
> 
> image

As it's a Polymorphic VI, it shows the terminals of the first element. The HLD documentation says that the terminal should be named the following way: <protocol_name> settings

**Comment by zszilagy** [comment]
> > > Please add documentation (one-liner) for each VI. Don't describe each terminal.
> > 
> > 
> > Fixed as requested.
> 
> Please make sure "RS-xxx Factory.vi" and "AK RS-xxx Factory.vi" both have a one liner documentation. Diff Bot does not show anything for this two VIs.

Both files have documentation but diffbot missed it:

image

image

**Review by phutanu — APPROVED** [review]

**Pull request merged**
